ALTER TABLE AD_ACADEMIC_SESSION ADD CONSTRAINT AD_ACADEMIC_SESSION_PK PRIMARY KEY ( SESSION_ID ) ;

ALTER TABLE AD_COURSE_DETAILS ADD CONSTRAINT AD_COURSE_DETAILS_PK PRIMARY KEY ( COURSE_ID ) ;

ALTER TABLE AD_DEPARTMENTS ADD CONSTRAINT AD_DEPARTMENT_PK PRIMARY KEY ( DEPARTMENT_ID ) ;

ALTER TABLE AD_EXAM_DETAILS ADD CONSTRAINT AD_EXAM_DETAILS_PK PRIMARY KEY ( EXAM_ID ) ;

ALTER TABLE AD_EXAM_TYPE ADD CONSTRAINT AD_EXAM_TYPE_PK PRIMARY KEY ( EXAM_TYPE ) ;

ALTER TABLE AD_JOBS ADD CONSTRAINT AD_JOBS_PK PRIMARY KEY ( JOB_ID ) ;

ALTER TABLE AD_FACULTY_DETAILS ADD CONSTRAINT AD_FACULTY_DETAILS_PK PRIMARY KEY ( FACULTY_ID ) ;

ALTER TABLE AD_FACULTY_DETAILS ADD CONSTRAINT AD_FACULTY_DETAILS_FK FOREIGN KEY (JOB_ID) REFERENCES AD_JOBS (JOB_ID);

ALTER TABLE AD_PARENT_INFORMATION ADD CONSTRAINT AD_PARENT_INFORMATION_PK PRIMARY KEY ( PARENT_ID ) ;

ALTER TABLE AD_STUDENT_DETAILS ADD CONSTRAINT AD_STUDENT_DETAILS_PK PRIMARY KEY ( STUDENT_ID ) ;

ALTER TABLE AD_COURSE_DETAILS ADD CONSTRAINT AD_COURSE_DETAILS_FK FOREIGN KEY ( SESSION_ID ) REFERENCES AD_ACADEMIC_SESSION ( SESSION_ID ) ;

ALTER TABLE AD_COURSE_DETAILS ADD CONSTRAINT AD_COURSE_DETAILS_FKv2 FOREIGN KEY ( DEPARTMENT_ID ) REFERENCES AD_DEPARTMENTS ( DEPARTMENT_ID ) ;

ALTER TABLE AD_EXAM_DETAILS ADD CONSTRAINT AD_EXAM_DETAILS_FK FOREIGN KEY ( EXAM_TYPE ) REFERENCES AD_EXAM_TYPE ( EXAM_TYPE ) ;

ALTER TABLE AD_EXAM_RESULTS ADD CONSTRAINT AD_EXAM_RESULTS_FK FOREIGN KEY ( COURSE_ID ) REFERENCES AD_COURSE_DETAILS ( COURSE_ID ) ;

ALTER TABLE AD_EXAM_RESULTS ADD CONSTRAINT AD_EXAM_RESULTS_FKv2 FOREIGN KEY ( EXAM_ID ) REFERENCES AD_EXAM_DETAILS ( EXAM_ID ) ;

ALTER TABLE AD_FACULTY_COURSE_DETAILS ADD CONSTRAINT AD_FACULTY_COURSE_DETAILS_FK FOREIGN KEY ( FACULTY_ID ) REFERENCES AD_FACULTY_DETAILS ( FACULTY_ID ) ;

ALTER TABLE AD_FACULTY_COURSE_DETAILS ADD CONSTRAINT AD_FACULTY_COURSE_DETAILS_FKv2 FOREIGN KEY (  COURSE_ID ) REFERENCES AD_COURSE_DETAILS ( COURSE_ID ) ;

ALTER TABLE AD_FACULTY_LOGIN_DETAILS ADD CONSTRAINT AD_FACULTY_LOGIN_DETAILS_FK FOREIGN KEY ( FACULTY_ID ) REFERENCES AD_FACULTY_DETAILS ( FACULTY_ID ) ;

ALTER TABLE AD_STUDENT_ATTENDANCE ADD CONSTRAINT AD_STUDENT_ATTENDANCE_FK FOREIGN KEY ( STUDENT_ID ) REFERENCES AD_STUDENT_DETAILS ( STUDENT_ID ) ;

ALTER TABLE AD_STUDENT_COURSE_DETAILS ADD CONSTRAINT AD_STUDENT_COURSE_DETAILS_FK FOREIGN KEY ( STUDENT_ID ) REFERENCES AD_STUDENT_DETAILS ( STUDENT_ID ) ;

ALTER TABLE AD_STUDENT_COURSE_DETAILS ADD CONSTRAINT AD_STUDENT_COURSE_DETAILS_FKv2 FOREIGN KEY ( COURSE_ID ) REFERENCES AD_COURSE_DETAILS ( COURSE_ID ) ;

ALTER TABLE AD_STUDENT_DETAILS ADD CONSTRAINT AD_STUDENT_DETAILS_FK FOREIGN KEY ( PARENT_ID ) REFERENCES AD_PARENT_INFORMATION ( PARENT_ID ) ;


ALTER TABLE AD_STUDENT_DETAILS ADD ( EMAIL_ADDR VARCHAR2(100) UNIQUE );


ALTER TABLE AD_FACULTY_LOGIN_DETAILS  MODIFY ( LOGIN_DATE DATE DEFAULT SYSDATE );
ALTER TABLE AD_PARENT_INFORMATION  READ ONLY;

