DROP TABLE AD_STUDENT_ATTENDANCE ;

DROP TABLE AD_STUDENT_COURSE_DETAILS ;

DROP TABLE AD_STUDENT_DETAILS ;

DROP TABLE AD_FACULTY_LOGIN_DETAILS ;

DROP TABLE AD_FACULTY_COURSE_DETAILS ;

DROP TABLE AD_EXAM_RESULTS ;

DROP TABLE AD_COURSE_DETAILS ;
	
DROP TABLE AD_EXAM_DETAILS ;

DROP TABLE AD_PARENT_INFORMATION ;

DROP TABLE AD_EXAM_TYPE ;

DROP TABLE AD_DEPARTMENTS ;

DROP TABLE AD_FACULTY_DETAILS ;

DROP TABLE AD_JOBS;

DROP TABLE AD_ACADEMIC_SESSION ;

